### ISSUE TITLE
go-worker fails to build with go 1.24.2

### ISSUE THREAD

**Issue by RossComputerGuy** [austinlparker/otelbrot#6]
```
otelbrot-go-worker> Running phase: checkPhase
otelbrot-go-worker> ok  	github.com/austinlparker/otelbrot/go-worker/internal/calculator	0.010s
otelbrot-go-worker> # github.com/austinlparker/otelbrot/go-worker/internal/config [github.com/austinlparker/otelbrot/go-worker/internal/config.test]
otelbrot-go-worker> internal/config/config_test.go:45:20: too many arguments in call to Load
otelbrot-go-worker> 	have (string)
otelbrot-go-worker> 	want ()
otelbrot-go-worker> internal/config/config_test.go:113:20: too many arguments in call to Load
otelbrot-go-worker> 	have (string)
otelbrot-go-worker> 	want ()
otelbrot-go-worker> internal/config/config_test.go:147:18: too many arguments in call to Load
otelbrot-go-worker> 	have (string)
otelbrot-go-worker> 	want ()
otelbrot-go-worker> internal/config/config_test.go:171:17: too many arguments in call to Load
otelbrot-go-worker> 	have (string)
otelbrot-go-worker> 	want ()
otelbrot-go-worker> FAIL	github.com/austinlparker/otelbrot/go-worker/internal/config [build failed]
otelbrot-go-worker> FAIL
```
Tried building tests and these failed.
